name: 프론트엔드 CI

on:
  push:
    branches: [ main, dev, 'release/*' ]
    paths:
      - 'front/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main, dev, 'release/*' ]
    paths:
      - 'front/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4

      - name: Node.js 20을 설치합니다.
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: 의존성 설치
        run: npm ci

      - name: npm run build
        run: npm run build
